services:
  db:
    image: postgres:15-alpine 
    container_name: master-chef-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - vol_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-master-network

  app:
    build: ./backend/src/master-chef/demo/
    container_name: master-chef-app
    ports:
      - "8080:8080"
    environment:
      API_TOKEN: ${API_TOKEN}
      URL: ${URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      - db
    networks:
      - app-master-network

  web:
    build: ./frontend/src/
    container_name: master-chef-frontend
    ports:
      - "4200:4200"
    environment:
      REACT_APP_API_URL: http://app:8080
    depends_on:
      - app
    networks:
      - app-master-network

volumes:
  vol_postgres_data:

networks:
  app-master-network: 
    external: false